export { default as Canvas } from './canvas'
export { default as Layer } from './layer'
export { default as header } from './header'
export { default as slider } from './slider'
export { default as panelsTools } from './panelsTools'
